[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
rustrict = "0.7.31"
serenity = "0.12.2"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
